version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn -DskipTests package
  post_build:
    commands:
      - mvn test
      - mv ./target/*.war ./target/ROOT.war
artifacts:
  files:
    - ./target/*.war
  discard-paths: yes
